routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;
use App\Http\Controllers\PermisosController 	AS Permisos;
use App\Http\Controllers\ModulosController 		AS Modulos;
use App\Http\Controllers\RolesController 		AS Roles;
use App\Http\Controllers\Auth\LoginController	AS Login;
use App\Http\Controllers\UserController 		AS Usuarios;
use App\Http\Controllers\PersonasController 	AS Personas;
use App\Http\Controllers\ReferidoController 	AS Referidos;
use App\Http\Controllers\PreguntasController 	AS Preguntas;
use App\Http\Controllers\BitacorasController 	AS Bitacoras;
use App\Http\Controllers\HomeController			AS Home;

use App\Http\Controllers\ApplicationController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|


Route::get('login/{provider}', [Login::class, 'redirectToProvider'])->name('social.auth');
Route::get('login/{provider}/callback', [Login::class, 'handleProviderCallback'])->name('social.callback');

Auth::routes();

Route::get('/', function () {
	if(Auth::guest()){
    	return view('auth.login');
	}else{
        return redirect()->route('home')->with('status_success', 'Se ha iniciado sesion recientemente');
	}
});

//Route::get('/home', [Home::class, 'index'])->name('home');



Route::get('/perfil', [Personas::class, 'perfil'])->name('perfil');
Route::get('/perfil/usuario', [Personas::class, 'perfilUnico'])->name('perfin.usuario');
Route::post('/perfil/store', [Personas::class, 'perfilStore'])->name('perfil.store');


Route::resource('/permisos', Permisos::class)->names('permisos');


Route::resource('/modulos', Modulos::class)->names('modulos');


Route::resource('/usuarios', Usuarios::class)->names('users');

Route::get('/asignacion_permisos/update/{id?}', [Permisos::class, 'edit'])->name('asignacion.edit');
Route::post('/asignacion_permisos/update/permiso/{id?}', [Permisos::class, 'update'])->name('asignacion.update');


Route::resource('/personas', Personas::class)->names('personas');

Route::resource('/referidos', Referidos::class)->names('referidos');


Route::get('/tipo_clientes/{id}', [Referidos::class, 'tipo_clientes']);

Route::resource('/preguntas', Preguntas::class)->names('preguntas');

Route::resource('/bitacoras', Bitacoras::class)->names('bitacoras');
Route::get('/generar/{cedula}', [Bitacoras::class, 'generar'])->name('generar');
Route::get('/generar/acciones/{valor}/{bitacora}', [Bitacoras::class, 'acciones'])->name('acciones');
Route::post('/registro/acciones', [Bitacoras::class, 'registro']);
Route::get('/informacion/referido/{cedula}', [Bitacoras::class, 'informacion_referido']);


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::post('/login', [Login::class, 'login'])->name('login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout')->middleware('auth:api');
Route::post('/register', 'Auth\RegisterController@register')->name('register');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.reset');*/



/*
|--------------------------------------------------------------------------
| Laravel Passport Routes
|--------------------------------------------------------------------------
|
| If you'd like to use full functionality of laravel passport
| use the routes below instead of registering your routes in
| AuthServiceProvider as instructed in passport documentation.
| This will use "auth:api" guard instead of "auth"
|

Route::get('oauth/authorize', '\Laravel\Passport\Http\Controllers\AuthorizationController@authorize')->middleware('auth:api');
Route::delete('oauth/authorize', '\Laravel\Passport\Http\Controllers\DenyAuthorizationController@deny')->middleware('auth:api');
Route::post('oauth/authorize', '\Laravel\Passport\Http\Controllers\ApproveAuthorizationController@approve')->middleware('auth:api');

Route::get('oauth/clients', '\Laravel\Passport\Http\Controllers\ClientController@forUser')->middleware('auth:api');
Route::post('oauth/clients', '\Laravel\Passport\Http\Controllers\ClientController@store')->middleware('auth:api');
Route::put('oauth/clients/{client_id}', '\Laravel\Passport\Http\Controllers\ClientController@update')->middleware('auth:api');
Route::delete('oauth/clients/{client_id}', '\Laravel\Passport\Http\Controllers\ClientController@destroy')->middleware('auth:api');

Route::post('oauth/personal-access-tokens', '\Laravel\Passport\Http\Controllers\PersonalAccessTokenController@store')->middleware('auth:api');
Route::get('oauth/personal-access-tokens', '\Laravel\Passport\Http\Controllers\PersonalAccessTokenController@forUser')->middleware('auth:api');
Route::delete('oauth/personal-access-tokens/{token_id}', '\Laravel\Passport\Http\Controllers\PersonalAccessTokenController@destroy')->middleware('auth:api');

Route::get('oauth/scopes', '\Laravel\Passport\Http\Controllers\ScopeController@all')->middleware('auth:api');
Route::post('oauth/token/refresh', '\Laravel\Passport\Http\Controllers\TransientTokenController@refresh')->middleware('auth:api');
Route::get('oauth/tokens', '\Laravel\Passport\Http\Controllers\AuthorizedAccessTokenController@forUser')->middleware('auth:api');
Route::delete('oauth/tokens/{token_id}', '\Laravel\Passport\Http\Controllers\AuthorizedAccessTokenController@destroy')->middleware('auth:api');

*/

//Auth::routes();
//Route::get('oauth/scopes', '\Laravel\Passport\Http\Controllers\ScopeController@all')->middleware('auth:api');

Route::get('/{any}', [ApplicationController::class, 'index'])->where('any', '.*');

app/Http/Controllers/BitacorasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\AddyPersona      as Personas;
use App\Models\AddyEstado       as Estados;
use App\Models\AddyBitacora     as Bitacoras;
use App\Models\User             as Usuarios;
use App\Models\AddyAccione      as Acciones;
use App\Models\AddyHistoriale   as Historiales;
use App\Models\AddyFormulario   as Formularios;


use DB;
use Gate;

class BitacorasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        
        Gate::authorize('haveaccess','permisos.habilitado.bitacoras');


        $informacion = DB::table('role_user')
                        ->select('role_user.role_id','role_user.user_id', 'users.id', 'users.name', 'roles.id', 'roles.nombre', 'roles.slug')
                        ->join('users', 'role_user.user_id', '=', 'users.id')
                        ->join('roles', 'role_user.role_id', '=', 'roles.id')
                        ->where('user_id', auth()->user()->id)
                        ->get();
        
        $usuarios_creadores = [];
        $acciones_bitacora = [];
        $estados_bitacora = [];

        if($informacion[0]->slug == 'administrator'){
            $bitacoras = Bitacoras::all();
        }else{

            $bitacoras = Bitacoras::where('id_creador', auth()->user()->id)->get();
        }

        foreach ($bitacoras as $bitacora) {
            $usuarios_creadores[]   = $bitacoras[0]->id_creador;
            $acciones_bitacora[]    = $bitacoras[0]->id_accion;
            $estados_bitacora[]     = $bitacoras[0]->id_estado;
        }

        $usuarios   = Usuarios::all();
        $acciones   = Acciones::all();
        $estados    = Estados::all();

        return view('pages.referidos.bitacoras.index', compact('bitacoras', 'usuarios' ,'acciones', 'estados', 'usuarios_creadores', 'acciones_bitacora', 'estados_bitacora'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function generar($cedula)
    {
        
        Gate::authorize('haveaccess','permisos.crear.bitacoras');

        $codigo = "AB-".time();
        $estados = Estados::where('modulo_estado', 'bitacoras')->get();
        return view('pages.referidos.bitacoras.crear', compact('codigo', 'estados', 'cedula'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Gate::authorize('haveaccess','permisos.crear.bitacoras');

        $rules = [
            'cedula'                => 'required',
            'code_bitacora'         => 'required',
            'descripcion_bitacora'  => 'required',
            'fecha_bitacora'        => 'required',
            'usuario_creador'       => 'required',
            'estado_bitacora'       => 'required',
        ];
        
        $messages = [
            'cedula.required'        => 'La cédula es importante.',
            'code_bitacora.required'        => 'El código de la Bitacora es importante.',
            'descripcion_bitacora.required' => 'Escriba una descripción de la Bitacora.',
            'fecha_bitacora.required'       => 'Ingrese la fecha de la Bitacora.',
            'usuario_creador.required'      => 'Es importante el usuario creador.',
            'estado_bitacora.required'      => 'Por favor seleccione el estado de la Bitacora.',
        ];

        $this->validate($request, $rules, $messages);

        Bitacoras::create([
            'codigo_bitacora'       => $request->code_bitacora,
            'descripcion_bitacora'  => $request->descripcion_bitacora,
            'fecha_bitacora'        => $request->fecha_bitacora,
            'id_creador'            => $request->usuario_creador,
            'cedula_persona'        => $request->cedula,
            'id_accion'             => '0',
            'id_estado'             => $request->estado_bitacora,
        ]);

        return redirect()->route('bitacoras.index')->with('status_success', 'Se ha registrado en nuestro sitema');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        Gate::authorize('haveaccess','permisos.ver.bitacoras');
        
        $bitacoras = Bitacoras::where('codigo_bitacora', $id)->get();
        
        foreach ($bitacoras as $bitacora) {
            $usuarios_creadores[]   = $bitacoras[0]->id_creador;
            $acciones_bitacora[]    = $bitacoras[0]->id_accion;
            $estados_bitacora[]     = $bitacoras[0]->id_estado;
        }

        $personas   = Personas::all();
        $usuarios   = Usuarios::all();
        $acciones   = Acciones::all();
        $estados    = Estados::where('modulo_estado', 'bitacoras')->get();
        $historiales    = Historiales::where('codigo_bitacora', $id)->orderBy('id', 'DESC')->get();

        return view('pages.referidos.bitacoras.ver', compact('bitacoras', 'usuarios' ,'acciones', 'estados', 'usuarios_creadores', 'acciones_bitacora', 'estados_bitacora', 'personas', 'historiales'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function acciones($valor, $bitacora){
        
        $informacion_bitacora   = Bitacoras::where('codigo_bitacora', $bitacora)->get();
        $informacion_persona    = Personas::where('cedula_persona', $informacion_bitacora[0]->cedula_persona)->get();
        

        if($valor == '1'){
            return view('pages.configuracion.acciones.registrar_llamada', compact('valor','informacion_bitacora' ,'informacion_persona'));
        }else if ($valor == '2') {
            return view('pages.configuracion.acciones.registro_cita_programada', compact('valor','informacion_bitacora' ,'informacion_persona'));
        }else{

        }
    }

    public function registro(Request $request){
        
        


        $rules = [
            'accion_realizada'              => 'required',
            'informacion_bitacora'          => 'required',

        ];
        
        $messages = [
            'accion_realizada.required'     => 'Seleccione un celular válido.',
            'informacion_bitacora.required'     => 'El código de la Bitacora es importante.',
        ];

        $this->validate($request, $rules, $messages);

        $acciones   = Acciones::where('codigo_accion', $request->accion_realizada)->count();


        if($acciones >= '1'){
            
            if($request->accion_realizada == '1'){
                $rules = [
                    'celular'               => 'required',
                    'hora_inicio'           => 'required',
                    'hora_fin'              => 'required',
                    'resultado_llamada'     => 'required',
                    'usuario_registro'      => 'required',
                    'fecha_registro'        => 'required',
                ];
            
                $messages = [
                    'celular.required'              => 'Seleccione un celular válido.',
                    'hora_inicio.required'          => 'La ahora de inicio es importante.',
                    'hora_fin.required'             => 'La hora final es Importante.',
                    'resultado_llamada.required'    => '¿Cual fue el resultado de la llamada?.',
                    'usuario_registro.required'     => 'El usuario es importante.',
                    'fecha_registro.required'       => 'Por favor, no deje vacio la fecha de registro.',
                ];

                $this->validate($request, $rules, $messages);    
                
                date_default_timezone_set('America/Bogota');

                Historiales::create([
                    'descripcion_historial' => 'Se realizo la acción de Regirar llamada al celular/fijo '.$request->celular." la hora de inicio fue: ".$request->hora_inicio." y la hora de fin fue: ".$request->hora_fin." y el resultado de la llamada fue: ".$request->resultado_llamada." con fecha del: ".$request->fecha_registro,
                    'codigo_bitacora'       => $request->informacion_bitacora,
                    'id_usuario'            => auth()->user()->id,
                    'fecha_historial'       => date('Y-m-d H:i'),
                ]);

            }else if($request->accion_realizada == '2'){
                $rules = [
                    'fecha_inicio'               => 'required',
                    'resultado_agenda'           => 'required',
                    'usuario_registro'      => 'required',
                    'fecha_registro'        => 'required',
                ];
            
                $messages = [
                    'fecha_inicio.required'              => 'Seleccione una fecha válida.',
                    'resultado_agenda.required'          => 'Describa el resultado que es importante.',
                    'usuario_registro.required'     => 'El usuario es importante.',
                    'fecha_registro.required'       => 'Por favor, no deje vacio la fecha de registro.',
                ];

                $this->validate($request, $rules, $messages);    
                

resources/views/pages/referidos/bitacoras/crear.blade.php
<?php date_default_timezone_set('America/Bogota'); ?>

<form id="formulario" action="{{ route('bitacoras.store') }}" method="POST">
	@method('POST')
	@csrf
	
	<div class="form-group">
		<label><b>(*) Asociar a:</b></label>
		<input type="text" class="form-control" name="cedula" value="{{ $cedula }}" readonly="">
	</div>

	<div class="form-group">
		<label><b>(*) Código Bitacora:</b></label>
		<input type="text" class="form-control" name="code_bitacora" value="{{ $codigo }}" readonly="">
	</div>

	<div class="form-group">
		<label><b>(*) Descripción de la Bitacora:</b></label>
		<textarea  name="descripcion_bitacora" class="form-control"></textarea>
	</div>

	<div class="form-group">
		<label><b>(*) Fecha de creación:</b></label>
		<input type="datetime" class="form-control" name="fecha_bitacora" value="{{ date('Y-m-d H:i:s') }}" readonly="">
	</div>

	<div class="form-group">
		<label><b>(*) Usuario creador:</b></label>
		<input type="hidden" class="form-control" name="usuario_creador" value="{{ auth()->user()->id }}">
		<input type="text" class="form-control"value="{{ auth()->user()->name }}" readonly="">
	</div>

	<div class="form-group">
		<label><b>(*) Estado Bitacora:</b></label>
		<select class="form-control" name="estado_bitacora">
			@foreach($estados as $estado)
				<option value="{{ $estado->id }}">{{ $estado->nombre_estado }}</option>
			@endforeach
		</select>
	</div>
	<br>
	<center>
		<input type="submit" class="btn btn-success" value="Crear">
	</center>
</form>

resources/views/pages/referidos/bitacoras/index.blade.php
@extends('layouts.app')

@section('title', 'Módulo Persona')

@section('content')
<div class="content-wrapper">
    <div class="content-header row">
    </div>
    <div class="content-body">

    	@include('pages.configuracion.mensajes.alertas')

        <section id="dashboard-ecommerce">
            <div class="row match-height">
                <div class="col-12 col-sm-12 col-xl-12 col-lg-12">
                    <div class="card card-congratulation-medal">
                        <div class="card-body">
                            <h3>Bitacoras</h3>
                            <p class="card-text font-small-3">Hola! acá verás un listado con todos los referidos registrados.</p>
                            <!--<h3 class="mb-75 mt-2 pt-50">
                                    <a href="javascript:void(0);">$48.9k</a>
                            </h3>-->
                            <hr>

                            <div class="panel-busqueda">
                                <div class="row">
                                    <div class="form-group col-12 col-md-9 col-lg-9 col-sm-9 col-xl-9 col-lg-9">
                                        <label><b>Búsqueda de Bitacoras:</b></label>
                                        <input type="text" class="form-control" name="busqueda_empresa" id="busqueda" data-modulo="empresas">
                                    </div>
                                    <div class="form-group col-12 col-md-3 col-lg-3 col-sm-3 col-xl-3 col-lg-3">
                                        <label></label>
                                        <button class="btn btn-primary btn-block waves-effect waves-float waves-light" tabindex="4">Búsqueda avanzada</button>
                                    </div>
                                </div>
                                <table class="table table-bordered table-responsive ">
                                    <thead>
                                        <tr>
                                        	<th>Código Bitácora </th>
                                            <th>Descripción Bitácora</th>
                                            <th>Fecha creación Bitácora</th>
                                            <th>Creador</th>
                                            <th>Acción realizada</th>
                                            <th>Estado actual</th>
                                            <th colspan="1" style="text-align: center;">Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    	@foreach($bitacoras as $bitacora)
                                    	<tr>
                                    		<td>{{ $bitacora->codigo_bitacora }}</td>
                                    		<td>{{ $bitacora->descripcion_bitacora }}</td>
                                    		<td>{{ $bitacora->fecha_bitacora }}</td>
                                    		<td>
                                    		@foreach($usuarios as $usuario)
        										@if(is_array($usuarios_creadores) && in_array($usuario->id, $usuarios_creadores))
        											{{ $usuario->name }}
        										@endif
                                    		@endforeach
                                    		</td>
                                    		<td>
                                    		@foreach($acciones as $accion)
        										@if(is_array($acciones_bitacora) && in_array($accion->codigo_accion, $acciones_bitacora))
        											{{ $accion->descripcion_accion }}
        										@endif
                                    		@endforeach
                                    		</td>
                                    		<td>
                                    		@foreach($estados as $estado)
        										@if(is_array($estados_bitacora) && in_array($estado->id, $estados_bitacora))
        											{{ $estado->nombre_estado }}
        										@endif
                                    		@endforeach
                                    		</td>
                                    		<td>
                                                <a href="{{ route('bitacoras.show', $bitacora->codigo_bitacora) }}">
                                                    <button type="button" class="btn btn-info"> 
                                                        Ver
                                                    </button>
                                                </a>
	                                       	</td>
	                                    </tr>
	                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

@include('pages.configuracion.mensajes.modales')

@endsection

resources/views/pages/referidos/bitacoras/informacion_referidos.blade.php
<div class="row">
	<div class="col">
		<label><b>Cédula persona</b></label><br>
		{{ $persona[0]->cedula_persona }}
	</div>
	<div class="col">
		<label><b>Nombres persona</b></label><br>
		{{ $persona[0]->nombres_persona }}
	</div>
	<div class="col">
		<label><b>Apellidos persona</b></label><br>
		{{ $persona[0]->apellidos_persona }}
	</div>
	<div class="col">
	<label><b>Fecha de nacimiento</b></label><br>
		{{ $persona[0]->fecha_nacimiento }}
	</div>
</div>
<hr>
<div class="row">
	<div class="col">
		<label><b>Correo persona</b></label><br>
		{{ $persona[0]->correo_persona }}
	</div>
	<div class="col">
		<label><b>Telefono fijo</b></label><br>
		{{ $persona[0]->telefono_fijo }}
	</div>
	<div class="col">
		<label><b>Celular</b></label><br>
		{{ $persona[0]->celular_movil }}
	</div>
	<div class="col">
		<label><b>Whatsapp persona</b></label><br>
		{{ $persona[0]->celular_whatsapp }}
	</div>
</div>

<hr>
<div class="row">
	<div class="col">
		<label><b>Dirección persona</b></label><br>
		{{ $persona[0]->direccion_persona }}
	</div>
	<div class="col">
		<label><b>Pais persona</b></label><br>
		{{ $persona[0]->telefono_fijo }}
	</div>
	<div class="col">
		<label><b>Ciudad Persona</b></label><br>
		{{ $persona[0]->celular_movil }}
	</div>
	<div class="col">
		<label><b>Código Postal</b></label><br>
		{{ $persona[0]->celular_whatsapp }}
	</div>
</div>


<hr>
<div class="row">
	<div class="col">
		<label><b>cedula Agente</b></label><br>
		{{ $persona[0]->nit_empresa }}
	</div>
</div>

<hr>
<div class="row">
	<div class="col">
		<h4><b>Cuestionario:</b></h4>
	</div>
</div>

@foreach($formularios as $formulario)
<div class="row">
	<div class="container">
		<textarea class="form-control" readonly="">{{ $formulario->pregunta }}</textarea>
		<br>
		{{ $formulario->respuesta }}
	</div>
</div>
<hr>
@endforeach

resources/views/pages/referidos/bitacoras/ver.blade.php
@extends('layouts.app')

@section('title', 'Información Bitácora')

@section('content')
<div class="content-wrapper">
    <div class="content-header row">
    </div>
    <div class="content-body">

    	@include('pages.configuracion.mensajes.alertas')

        <section id="dashboard-ecommerce">
            <div class="row match-height">
                <div class="col-12 col-sm-12 col-xl-12 col-lg-12">
                    <div class="card card-congratulation-medal">
                        <div class="card-body">
                            <div class="row">
                            	<div class="col">
                            		<h3>Información detallada</h3>		
                            	</div>
                            	<div class="row col">
                            		<div class="form-group col-4">
                            			<label><b>Última acción realizada:</b></label>
                            			<select class="form-control accion_bitacora" data-bitacora="{{ $bitacoras[0]->codigo_bitacora }}">
                            			@foreach($acciones as $accion)
                            				@if(is_array($acciones_bitacora) && in_array($accion->codigo_accion, $acciones_bitacora))
                            					<option value="{{ $accion->codigo_accion }}" selected="">{{ $accion->descripcion_accion }}</option>
        									@else
                            					<option value="{{ $accion->codigo_accion }}">{{ $accion->descripcion_accion }}</option>
        									@endif
                                    	@endforeach
                            		</select>
                            		</div>
                            		<div class="form-group col-4">
                            			<label><b>Estado bitácora:</b></label>
                            		<select class="form-control btn btn-success">
                            			@foreach($estados as $estado)
                            				@if(is_array($estados_bitacora) && in_array($estado->id, $estados_bitacora))
                            					<option value="{{ $estado->id }}" selected="">{{ $estado->nombre_estado }}</option>
        									@else
                            					<option value="{{ $estado->id }}">{{ $estado->nombre_estado }}</option>
        									@endif
                                    	@endforeach
                            		</select>
                            		</div>	

                            	</div>
                            </div>
                            

                            <!--
                            <p class="card-text font-small-3">Hola! acá verás un listado con todos los referidos registrados.</p>-->
                            <!--<h3 class="mb-75 mt-2 pt-50">
                                    <a href="javascript:void(0);">$48.9k</a>
                            </h3>-->
                            <hr>

                            <!--
                            <div class="panel-busqueda">
                                <div class="row">
                                    <div class="form-group col-12 col-md-9 col-lg-9 col-sm-9 col-xl-9 col-lg-9">
                                        <label><b>Búsqueda de Bitacoras:</b></label>
                                        <input type="text" class="form-control" name="busqueda_empresa" id="busqueda" data-modulo="empresas">
                                    </div>
                                    <div class="form-group col-12 col-md-3 col-lg-3 col-sm-3 col-xl-3 col-lg-3">
                                        <label></label>
                                        <button class="btn btn-primary btn-block waves-effect waves-float waves-light" tabindex="4">Búsqueda avanzada</button>
                                    </div>
                                </div>

                            </div>-->
                            <div class="row">
                                <div class="col">
                                    <h5>Referido asociado</h5>
                                    <hr>
                                    <p>
                                        @foreach($personas as $persona)
                                            @if($persona->cedula_persona == $bitacoras[0]->cedula_persona)
                                                <button type="button" class="btn btn-info informacion_referido" data-cedula="{{ $bitacoras[0]->cedula_persona }}"> 
                                                    {{ $persona->cedula_persona }} - {{  $persona->nombres_persona }} {{ $persona->apellidos_persona }}
                                                </button>
                                            @endif
                                        @endforeach
                                    </p>
                                </div>
                            	<div class="col">
                            		<h5>Descripción Bitácora</h5>
                            		<hr>
                            		<p>
                            			{{ $bitacoras[0]->descripcion_bitacora }}
                            		</p>
                            	</div>
                            	<div class="col">
                            		<h5>Fecha creación Bitácora</h5>
                            		<hr>
                            		<p>
                            			{{ $bitacoras[0]->fecha_bitacora }}
                            		</p>
                            	</div>
                            	<div class="col">
                            		<h5>Código Bitácora</h5>
                            		<hr>
                            		<p>
                            			<button type="button" class="btn btn-danger">
                            				{{ $bitacoras[0]->codigo_bitacora }}
                            			</button>
                            		</p>
                            	</div>
                            </div>

                        </div>
                    </div>
                    <div class="card card-congratulation-medal">
                        <div class="card-body">
                            <div class="row">
                                <div class="col">
                                    <h3>Historial</h3>      
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="container">
                                @foreach($historiales as $historial)
                                    <input type="text" class="form-control" readonly="" value="Fecha registro: {{ $historial->fecha_historial }}">
                                    <p class="btn"><i>{{ $historial->descripcion_historial }}</i></p>
                                    <hr>
                                @endforeach
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

@include('pages.configuracion.mensajes.modales')

@endsection